-- Arsenal farmacológico — pegar en Supabase SQL Editor y Run
-- (correr UNA sola vez; la tabla medications ya existe y está vacía)

-- Arsenal HCSFB Bulnes v1 (387 medicamentos)
insert into public.medications (name, active_ingredient, presentation, dose_value, dose_unit, category, is_active) values
  ('Acenocumarol', 'Acenocumarol', 'Comprimido', 4, 'mg', 'Anticoagulante', true),
  ('Warfarina', 'Warfarina', 'Comprimido', 5, 'mg', 'Anticoagulante', true),
  ('Heparina sódica', 'Heparina sódica', 'Solución inyectable', 5000, 'UI/mL', 'Anticoagulante', true),
  ('Enoxaparina', 'Enoxaparina', 'Solución inyectable', 40, 'mg', 'Anticoagulante', true),
  ('Enoxaparina', 'Enoxaparina', 'Solución inyectable', 80, 'mg', 'Anticoagulante', true),
  ('Clopidogrel', 'Clopidogrel', 'Comprimido', 75, 'mg', 'Antiagregante', true),
  ('Ácido acetilsalicílico', 'Ácido acetilsalicílico', 'Comprimido', 100, 'mg', 'Antiagregante', true),
  ('Ácido acetilsalicílico', 'Ácido acetilsalicílico', 'Comprimido', 500, 'mg', 'Analgésico', true),
  ('Acetazolamida', 'Acetazolamida', 'Comprimido', 250, 'mg', 'Diurético', true),
  ('Furosemida', 'Furosemida', 'Comprimido', 40, 'mg', 'Diurético', true),
  ('Furosemida', 'Furosemida', 'Solución inyectable', 20, 'mg/mL', 'Diurético', true),
  ('Hidroclorotiazida', 'Hidroclorotiazida', 'Comprimido', 50, 'mg', 'Diurético', true),
  ('Espironolactona', 'Espironolactona', 'Comprimido', 25, 'mg', 'Diurético', true),
  ('Aciclovir', 'Aciclovir', 'Comprimido', 200, 'mg', 'Antiviral', true),
  ('Aciclovir', 'Aciclovir', 'Comprimido', 400, 'mg', 'Antiviral', true),
  ('Oseltamivir', 'Oseltamivir', 'Comprimido', 75, 'mg', 'Antiviral', true),
  ('Oseltamivir', 'Oseltamivir', 'Suspensión oral', 12, 'mg/mL', 'Antiviral', true),
  ('Amikacina', 'Amikacina', 'Solución inyectable', 500, 'mg', 'Antibiótico', true),
  ('Amoxicilina', 'Amoxicilina', 'Comprimido', 500, 'mg', 'Antibiótico', true),
  ('Amoxicilina', 'Amoxicilina', 'Suspensión oral', 500, 'mg/5mL', 'Antibiótico', true),
  ('Amoxicilina + Ácido clavulánico', 'Amoxicilina + Ácido clavulánico', 'Comprimido', 625, 'mg', 'Antibiótico', true),
  ('Amoxicilina + Ácido clavulánico', 'Amoxicilina + Ácido clavulánico', 'Comprimido', 1000, 'mg', 'Antibiótico', true),
  ('Amoxicilina + Ácido clavulánico', 'Amoxicilina + Ácido clavulánico', 'Suspensión oral', 457, 'mg/5mL', 'Antibiótico', true),
  ('Ampicilina', 'Ampicilina', 'Polvo para solución inyectable', 500, 'mg', 'Antibiótico', true),
  ('Ampicilina + Sulbactam', 'Ampicilina + Sulbactam', 'Polvo para solución inyectable', 1500, 'mg', 'Antibiótico', true),
  ('Azitromicina', 'Azitromicina', 'Comprimido', 500, 'mg', 'Antibiótico', true),
  ('Azitromicina', 'Azitromicina', 'Suspensión oral', 200, 'mg/5mL', 'Antibiótico', true),
  ('Azitromicina', 'Azitromicina', 'Suspensión oral', 400, 'mg/5mL', 'Antibiótico', true),
  ('Bencilpenicilina', 'Bencilpenicilina', 'Polvo para solución inyectable', 1000000, 'UI', 'Antibiótico', true),
  ('Bencilpenicilina', 'Bencilpenicilina', 'Polvo para solución inyectable', 2000000, 'UI', 'Antibiótico', true),
  ('Cefadroxilo', 'Cefadroxilo', 'Comprimido', 500, 'mg', 'Antibiótico', true),
  ('Cefadroxilo', 'Cefadroxilo', 'Suspensión oral', 250, 'mg/5mL', 'Antibiótico', true),
  ('Cefazolina', 'Cefazolina', 'Polvo para solución inyectable', 1, 'g', 'Antibiótico', true),
  ('Ceftazidima', 'Ceftazidima', 'Polvo para solución inyectable', 1, 'g', 'Antibiótico', true),
  ('Ceftriaxona', 'Ceftriaxona', 'Polvo para solución inyectable', 1, 'g', 'Antibiótico', true),
  ('Ciprofloxacino', 'Ciprofloxacino', 'Comprimido', 500, 'mg', 'Antibiótico', true),
  ('Claritromicina', 'Claritromicina', 'Comprimido', 500, 'mg', 'Antibiótico', true),
  ('Claritromicina', 'Claritromicina', 'Suspensión oral', 250, 'mg/5mL', 'Antibiótico', true),
  ('Clindamicina', 'Clindamicina', 'Comprimido', 300, 'mg', 'Antibiótico', true),
  ('Clindamicina', 'Clindamicina', 'Solución inyectable', 600, 'mg', 'Antibiótico', true),
  ('Cloxacilina', 'Cloxacilina', 'Comprimido', 500, 'mg', 'Antibiótico', true),
  ('Cloxacilina', 'Cloxacilina', 'Polvo para solución inyectable', 500, 'mg', 'Antibiótico', true),
  ('Cotrimoxazol', 'Sulfametoxazol + Trimetoprim', 'Comprimido', 960, 'mg', 'Antibiótico', true),
  ('Cotrimoxazol', 'Sulfametoxazol + Trimetoprim', 'Solución inyectable', 480, 'mg', 'Antibiótico', true),
  ('Doxiciclina', 'Doxiciclina', 'Comprimido', 100, 'mg', 'Antibiótico', true),
  ('Estreptomicina', 'Estreptomicina', 'Polvo para solución inyectable', 1, 'g', 'Antibiótico', true),
  ('Flucloxacilina', 'Flucloxacilina', 'Jarabe', 250, 'mg/5mL', 'Antibiótico', true),
  ('Gentamicina', 'Gentamicina', 'Solución inyectable', 40, 'mg/mL', 'Antibiótico', true),
  ('Imipenem + Cilastatina', 'Imipenem + Cilastatina', 'Polvo para solución inyectable', 1000, 'mg', 'Antibiótico', true),
  ('Levofloxacino', 'Levofloxacino', 'Comprimido', 500, 'mg', 'Antibiótico', true),
  ('Meropenem', 'Meropenem', 'Polvo para solución inyectable', 500, 'mg', 'Antibiótico', true),
  ('Metronidazol', 'Metronidazol', 'Comprimido', 500, 'mg', 'Antibiótico', true),
  ('Metronidazol', 'Metronidazol', 'Solución inyectable', 500, 'mg', 'Antibiótico', true),
  ('Nitrofurantoína', 'Nitrofurantoína', 'Cápsula', 100, 'mg', 'Antibiótico', true),
  ('Penicilina G Benzatina', 'Penicilina G Benzatina', 'Polvo para solución inyectable', 1200000, 'UI', 'Antibiótico', true),
  ('Piperacilina + Tazobactam', 'Piperacilina + Tazobactam', 'Polvo para solución inyectable', 4500, 'mg', 'Antibiótico', true),
  ('Vancomicina', 'Vancomicina', 'Polvo para solución inyectable', 500, 'mg', 'Antibiótico', true),
  ('Fluconazol', 'Fluconazol', 'Comprimido', 150, 'mg', 'Antifúngico', true),
  ('Clotrimazol', 'Clotrimazol', 'Crema', 1, '%', 'Antifúngico', true),
  ('Clotrimazol', 'Clotrimazol', 'Óvulo vaginal', 500, 'mg', 'Antifúngico', true),
  ('Nistatina', 'Nistatina', 'Suspensión oral', 100000, 'UI/mL', 'Antifúngico', true),
  ('Terbinafina', 'Terbinafina', 'Comprimido', 250, 'mg', 'Antifúngico', true),
  ('Isoniazida', 'Isoniazida', 'Comprimido', 100, 'mg', 'Antituberculoso', true),
  ('Etambutol', 'Etambutol', 'Comprimido', 400, 'mg', 'Antituberculoso', true),
  ('Pirazinamida', 'Pirazinamida', 'Comprimido', 500, 'mg', 'Antituberculoso', true),
  ('Rifampicina', 'Rifampicina', 'Comprimido', 150, 'mg', 'Antituberculoso', true),
  ('Rifampicina', 'Rifampicina', 'Solución oral', 100, 'mg/5mL', 'Antituberculoso', true),
  ('Rifapentina', 'Rifapentina', 'Comprimido', 150, 'mg', 'Antituberculoso', true),
  ('Darunavir', 'Darunavir', 'Comprimido', 800, 'mg', 'Antirretroviral', true),
  ('Lamivudina', 'Lamivudina', 'Solución oral', 50, 'mg/5mL', 'Antirretroviral', true),
  ('Raltegravir', 'Raltegravir', 'Comprimido', 400, 'mg', 'Antirretroviral', true),
  ('Ritonavir', 'Ritonavir', 'Comprimido', 100, 'mg', 'Antirretroviral', true),
  ('Tenofovir + Emtricitabina', 'Tenofovir + Emtricitabina', 'Comprimido', 500, 'mg', 'Antirretroviral', true),
  ('Tenofovir + Lamivudina + Dolutegravir', 'Tenofovir + Lamivudina + Dolutegravir', 'Comprimido', 650, 'mg', 'Antirretroviral', true),
  ('Zidovudina', 'Zidovudina', 'Solución oral', 50, 'mg/5mL', 'Antirretroviral', true),
  ('Zidovudina', 'Zidovudina', 'Comprimido', 300, 'mg', 'Antirretroviral', true),
  ('Albendazol', 'Albendazol', 'Comprimido', 200, 'mg', 'Antiparasitario', true),
  ('Albendazol', 'Albendazol', 'Suspensión oral', 200, 'mg/5mL', 'Antiparasitario', true),
  ('Permetrina', 'Permetrina', 'Shampoo', 1, '%', 'Antiparasitario', true),
  ('Deltametrina + Piperonil butóxido', 'Deltametrina + Piperonil butóxido', 'Loción', 12.5, '%', 'Antiparasitario', true),
  ('Ácido fólico', 'Ácido fólico', 'Comprimido', 1, 'mg', 'Suplemento', true),
  ('Ácido fólico', 'Ácido fólico', 'Comprimido', 5, 'mg', 'Suplemento', true),
  ('Cianocobalamina', 'Cianocobalamina', 'Solución inyectable', 0.1, 'mg/mL', 'Suplemento', true),
  ('Tiamina (Vitamina B1)', 'Tiamina (Vitamina B1)', 'Solución inyectable', 30, 'mg/mL', 'Suplemento', true),
  ('Piridoxina (Vitamina B6)', 'Piridoxina (Vitamina B6)', 'Comprimido', 50, 'mg', 'Suplemento', true),
  ('Piridoxina', 'Piridoxina', 'Solución inyectable', 100, 'mg/mL', 'Suplemento', true),
  ('Fitomenadiona (Vitamina K)', 'Fitomenadiona (Vitamina K)', 'Solución inyectable', 1, 'mg/mL', 'Suplemento', true),
  ('Fitomenadiona', 'Fitomenadiona', 'Solución inyectable', 10, 'mg/mL', 'Suplemento', true),
  ('Calcio carbonato', 'Calcio carbonato', 'Comprimido', 500, 'mg', 'Suplemento', true),
  ('Calcio + Vitamina D Forte', 'Calcio + Vitamina D Forte', 'Comprimido', 625, 'mg', 'Suplemento', true),
  ('Vitaminas A-C-D', 'Vitaminas A-C-D', 'Solución oral gotas', 1, 'gota', 'Suplemento', true),
  ('Zinc', 'Zinc', 'Solución oral', 5, 'mg/mL', 'Suplemento', true),
  ('Hierro sulfato', 'Hierro sulfato', 'Comprimido', 200, 'mg', 'Suplemento', true),
  ('Hierro bis-glicinato', 'Hierro bis-glicinato', 'Solución oral gotas', 6, 'mg/mL', 'Suplemento', true),
  ('Hierro sacarato', 'Hierro sacarato', 'Solución inyectable', 100, 'mg/5mL', 'Suplemento', true),
  ('Melatonina', 'Melatonina', 'Comprimido', 3, 'mg', 'Hipnótico', true),
  ('Paracetamol', 'Paracetamol', 'Comprimido', 500, 'mg', 'Analgésico', true),
  ('Paracetamol', 'Paracetamol', 'Comprimido', 160, 'mg', 'Analgésico', true),
  ('Paracetamol', 'Paracetamol', 'Solución inyectable', 10, 'mg/mL', 'Analgésico', true),
  ('Paracetamol', 'Paracetamol', 'Solución oral gotas', 100, 'mg/mL', 'Analgésico', true),
  ('Paracetamol', 'Paracetamol', 'Jarabe', 125, 'mg/5mL', 'Analgésico', true),
  ('Metamizol (Dipirona)', 'Metamizol (Dipirona)', 'Comprimido', 300, 'mg', 'Analgésico', true),
  ('Metamizol', 'Metamizol', 'Solución inyectable', 500, 'mg/mL', 'Analgésico', true),
  ('Metamizol', 'Metamizol', 'Supositorio', 250, 'mg', 'Analgésico', true),
  ('Ácido mefenámico', 'Ácido mefenámico', 'Comprimido', 500, 'mg', 'AINE', true),
  ('Diclofenaco', 'Diclofenaco', 'Comprimido', 50, 'mg', 'AINE', true),
  ('Diclofenaco', 'Diclofenaco', 'Solución inyectable', 25, 'mg/mL', 'AINE', true),
  ('Diclofenaco', 'Diclofenaco', 'Supositorio infantil', 12.5, 'mg', 'AINE', true),
  ('Ibuprofeno', 'Ibuprofeno', 'Comprimido', 400, 'mg', 'AINE', true),
  ('Ibuprofeno', 'Ibuprofeno', 'Suspensión oral', 200, 'mg/5mL', 'AINE', true),
  ('Ketoprofeno', 'Ketoprofeno', 'Comprimido', 50, 'mg', 'AINE', true),
  ('Ketorolaco', 'Ketorolaco', 'Comprimido', 10, 'mg', 'AINE', true),
  ('Ketorolaco', 'Ketorolaco', 'Comprimido', 30, 'mg', 'AINE', true),
  ('Ketorolaco', 'Ketorolaco', 'Solución inyectable', 30, 'mg/mL', 'AINE', true),
  ('Naproxeno', 'Naproxeno', 'Comprimido', 550, 'mg', 'AINE', true),
  ('Celecoxib', 'Celecoxib', 'Comprimido', 200, 'mg', 'AINE', true),
  ('Meloxicam', 'Meloxicam', 'Comprimido', 15, 'mg', 'AINE', true),
  ('Indometacina', 'Indometacina', 'Comprimido', 25, 'mg', 'AINE', true),
  ('Clonixinato de lisina', 'Clonixinato de lisina', 'Comprimido', 125, 'mg', 'Analgésico', true),
  ('Pargeverina', 'Pargeverina', 'Solución inyectable', 5, 'mg/mL', 'Antiespasmódico', true),
  ('Papaverina + Atropina', 'Papaverina + Atropina', 'Comprimido', 40, 'mg', 'Antiespasmódico', true),
  ('Propifenazona + Adifenina', 'Propifenazona + Adifenina', 'Supositorio', 490, 'mg', 'Analgésico', true),
  ('Butilbromuro de hioscina (Buscapina)', 'N-butilbromuro de hioscina', 'Solución inyectable', 20, 'mg/mL', 'Antiespasmódico', true),
  ('Tramadol', 'Tramadol', 'Comprimido', 50, 'mg', 'Opioide', true),
  ('Tramadol', 'Tramadol', 'Solución oral gotas', 100, 'mg/mL', 'Opioide', true),
  ('Tramadol', 'Tramadol', 'Solución inyectable', 100, 'mg/mL', 'Opioide', true),
  ('Morfina', 'Morfina', 'Solución inyectable', 10, 'mg/mL', 'Opioide', true),
  ('Morfina', 'Morfina', 'Solución inyectable', 20, 'mg/mL', 'Opioide', true),
  ('Morfina', 'Morfina', 'Solución oral gotas', 20, 'mg/mL', 'Opioide', true),
  ('Oxicodona', 'Oxicodona', 'Comprimido', 10, 'mg', 'Opioide', true),
  ('Metadona', 'Metadona', 'Comprimido', 10, 'mg', 'Opioide', true),
  ('Fentanilo', 'Fentanilo', 'Parche transdérmico', 25, 'µg/h', 'Opioide', true),
  ('Fentanilo', 'Fentanilo', 'Parche transdérmico', 50, 'µg/h', 'Opioide', true),
  ('Fentanilo', 'Fentanilo', 'Solución inyectable', 0.05, 'mg/mL', 'Opioide', true),
  ('Buprenorfina', 'Buprenorfina', 'Parche transdérmico', 35, 'µg/h', 'Opioide', true),
  ('Naloxona', 'Naloxona', 'Solución inyectable', 0.4, 'mg/mL', 'Antagonista opioide', true),
  ('Adenosina', 'Adenosina', 'Solución inyectable', 3, 'mg/mL', 'Antiarrítmico', true),
  ('Amiodarona', 'Amiodarona', 'Comprimido', 200, 'mg', 'Antiarrítmico', true),
  ('Amiodarona', 'Amiodarona', 'Solución inyectable', 50, 'mg/mL', 'Antiarrítmico', true),
  ('Atenolol', 'Atenolol', 'Comprimido', 50, 'mg', 'Betabloqueador', true),
  ('Bisoprolol', 'Bisoprolol', 'Comprimido', 2.5, 'mg', 'Betabloqueador', true),
  ('Carvedilol', 'Carvedilol', 'Comprimido', 6.25, 'mg', 'Betabloqueador', true),
  ('Carvedilol', 'Carvedilol', 'Comprimido', 12.5, 'mg', 'Betabloqueador', true),
  ('Carvedilol', 'Carvedilol', 'Comprimido', 25, 'mg', 'Betabloqueador', true),
  ('Propanolol', 'Propanolol', 'Comprimido', 10, 'mg', 'Betabloqueador', true),
  ('Propanolol', 'Propanolol', 'Comprimido', 40, 'mg', 'Betabloqueador', true),
  ('Propanolol', 'Propanolol', 'Solución inyectable', 1, 'mg/mL', 'Betabloqueador', true),
  ('Labetalol', 'Labetalol', 'Solución inyectable', 5, 'mg/mL', 'Antihipertensivo', true),
  ('Amlodipino', 'Amlodipino', 'Comprimido', 5, 'mg', 'Antihipertensivo', true),
  ('Amlodipino', 'Amlodipino', 'Comprimido', 10, 'mg', 'Antihipertensivo', true),
  ('Captopril', 'Captopril', 'Comprimido', 25, 'mg', 'IECA', true),
  ('Enalapril', 'Enalapril', 'Comprimido', 10, 'mg', 'IECA', true),
  ('Losartan', 'Losartán potásico', 'Comprimido', 50, 'mg', 'ARA-II', true),
  ('Hidralazina', 'Hidralazina', 'Comprimido', 50, 'mg', 'Antihipertensivo', true),
  ('Metildopa', 'Metildopa', 'Comprimido', 250, 'mg', 'Antihipertensivo', true),
  ('Nifedipino', 'Nifedipino', 'Comprimido liberación prolongada', 20, 'mg', 'Antihipertensivo', true),
  ('Diltiazem', 'Diltiazem', 'Comprimido', 60, 'mg', 'Antihipertensivo', true),
  ('Verapamilo', 'Verapamilo', 'Solución inyectable', 5, 'mg/2mL', 'Antiarrítmico', true),
  ('Doxazosina', 'Doxazosina', 'Comprimido', 4, 'mg', 'Antihipertensivo', true),
  ('Digoxina', 'Digoxina', 'Comprimido', 0.25, 'mg', 'Cardiotónico', true),
  ('Nitroglicerina', 'Nitroglicerina', 'Solución inyectable', 50, 'mg', 'Vasodilatador', true),
  ('Norepinefrina', 'Norepinefrina', 'Solución inyectable', 1, 'mg/mL', 'Vasopresor', true),
  ('Dopamina', 'Dopamina', 'Solución inyectable', 200, 'mg/5mL', 'Vasopresor', true),
  ('Epinefrina (Adrenalina)', 'Epinefrina (Adrenalina)', 'Solución inyectable', 1, 'mg/mL', 'Vasopresor', true),
  ('Efedrina', 'Efedrina', 'Solución inyectable', 60, 'mg/mL', 'Vasopresor', true),
  ('Atorvastatina', 'Atorvastatina', 'Comprimido', 20, 'mg', 'Hipolipemiante', true),
  ('Atorvastatina', 'Atorvastatina', 'Comprimido', 40, 'mg', 'Hipolipemiante', true),
  ('Gemfibrozilo', 'Gemfibrozilo', 'Comprimido', 600, 'mg', 'Hipolipemiante', true),
  ('Tenecteplase', 'Tenecteplase', 'Polvo para solución inyectable', 10000, 'UI', 'Trombolítico', true),
  ('Ácido tranexámico', 'Ácido tranexámico', 'Comprimido', 500, 'mg', 'Antifibrinolítico', true),
  ('Ácido tranexámico', 'Ácido tranexámico', 'Solución inyectable', 1000, 'mg/10mL', 'Antifibrinolítico', true),
  ('Insulina humana cristalina', 'Insulina humana cristalina', 'Solución inyectable', 100, 'UI/mL', 'Antidiabético', true),
  ('Insulina humana isófana (NPH)', 'Insulina humana isófana (NPH)', 'Suspensión inyectable', 100, 'UI/mL', 'Antidiabético', true),
  ('Glibenclamida', 'Glibenclamida', 'Comprimido', 5, 'mg', 'Antidiabético', true),
  ('Metformina', 'Metformina', 'Comprimido', 500, 'mg', 'Antidiabético', true),
  ('Metformina', 'Metformina', 'Comprimido', 850, 'mg', 'Antidiabético', true),
  ('Metformina', 'Metformina', 'Comprimido liberación prolongada', 1000, 'mg', 'Antidiabético', true),
  ('Vildagliptina', 'Vildagliptina', 'Comprimido', 50, 'mg', 'Antidiabético', true),
  ('Dapagliflozina', 'Dapagliflozina', 'Comprimido', 10, 'mg', 'Antidiabético', true),
  ('Levotiroxina', 'Levotiroxina', 'Comprimido', 50, 'µg', 'Hormona tiroidea', true),
  ('Levotiroxina', 'Levotiroxina', 'Comprimido', 100, 'µg', 'Hormona tiroidea', true),
  ('Omeprazol', 'Omeprazol', 'Cápsula', 20, 'mg', 'IBP', true),
  ('Omeprazol', 'Omeprazol', 'Solución inyectable', 40, 'mg', 'IBP', true),
  ('Ranitidina', 'Ranitidina', 'Comprimido', 300, 'mg', 'Antiulceroso', true),
  ('Ranitidina', 'Ranitidina', 'Solución inyectable', 10, 'mg/mL', 'Antiulceroso', true),
  ('Famotidina', 'Famotidina', 'Comprimido', 40, 'mg', 'Antiulceroso', true),
  ('Aluminio hidróxido', 'Aluminio hidróxido', 'Comprimido', 500, 'mg', 'Antiácido', true),
  ('Domperidona', 'Domperidona', 'Comprimido', 10, 'mg', 'Procinético', true),
  ('Domperidona', 'Domperidona', 'Solución oral gotas', 10, 'mg/mL', 'Procinético', true),
  ('Domperidona', 'Domperidona', 'Solución inyectable', 5, 'mg/mL', 'Procinético', true),
  ('Domperidona', 'Domperidona', 'Supositorio', 60, 'mg', 'Procinético', true),
  ('Metoclopramida', 'Metoclopramida', 'Comprimido', 10, 'mg', 'Antiemético', true),
  ('Metoclopramida', 'Metoclopramida', 'Solución inyectable', 5, 'mg/mL', 'Antiemético', true),
  ('Ondansetrón', 'Ondansetrón', 'Comprimido', 4, 'mg', 'Antiemético', true),
  ('Ondansetrón', 'Ondansetrón', 'Comprimido', 8, 'mg', 'Antiemético', true),
  ('Ondansetrón', 'Ondansetrón', 'Solución inyectable', 2, 'mg/mL', 'Antiemético', true),
  ('Doxilamina + Piridoxina', 'Doxilamina + Piridoxina', 'Comprimido', 20, 'mg', 'Antiemético', true),
  ('Lactulosa', 'Lactulosa', 'Solución oral', 65, '%', 'Laxante', true),
  ('Polietilenglicol (PEG)', 'Polietilenglicol (PEG)', 'Polvo', 17, 'g/sobre', 'Laxante', true),
  ('Picosulfato de sodio', 'Picosulfato de sodio', 'Cápsula', 2.5, 'mg', 'Laxante', true),
  ('Picosulfato de sodio', 'Picosulfato de sodio', 'Solución oral gotas', 7.5, 'mg/mL', 'Laxante', true),
  ('Glicerina', 'Glicerina', 'Supositorio', 2.5, 'g', 'Laxante', true),
  ('Loperamida', 'Loperamida', 'Comprimido', 2, 'mg', 'Antidiarreico', true),
  ('Carbón activado', 'Carbón activado', 'Polvo', 50, 'g', 'Antídoto', true),
  ('Lactobacillus rhamnosus', 'Lactobacillus rhamnosus', 'Cápsula', 75, 'mg', 'Probiótico', true),
  ('Salbutamol', 'Salbutamol', 'Inhalador', 100, 'µg/dosis', 'Broncodilatador', true),
  ('Salbutamol', 'Salbutamol', 'Solución para nebulización', 5, 'mg/mL', 'Broncodilatador', true),
  ('Ipratropio', 'Ipratropio', 'Inhalador', 0.02, 'mg/dosis', 'Broncodilatador', true),
  ('Ipratropio', 'Ipratropio', 'Solución para nebulización', 0.25, 'mg/mL', 'Broncodilatador', true),
  ('Budesonida', 'Budesonida', 'Inhalador', 200, 'µg/dosis', 'Corticoide inhalado', true),
  ('Fluticasona + Salmeterol', 'Fluticasona + Salmeterol', 'Inhalador', 125, 'µg/dosis', 'Combinación inhalada', true),
  ('Fluticasona + Salmeterol', 'Fluticasona + Salmeterol', 'Inhalador', 250, 'µg/dosis', 'Combinación inhalada', true),
  ('Salmeterol', 'Salmeterol', 'Inhalador', 25, 'µg/dosis', 'Broncodilatador', true),
  ('Mometasona furoato', 'Mometasona furoato', 'Suspensión nasal', 50, 'µg/dosis', 'Corticoide nasal', true),
  ('Dexametasona', 'Dexametasona', 'Comprimido', 4, 'mg', 'Corticoide', true),
  ('Dexametasona', 'Dexametasona', 'Solución inyectable', 4, 'mg/mL', 'Corticoide', true),
  ('Betametasona dipropionato', 'Betametasona dipropionato', 'Crema', 0.05, '%', 'Corticoide tópico', true),
  ('Betametasona fosfato', 'Betametasona fosfato', 'Solución inyectable', 4, 'mg/mL', 'Corticoide', true),
  ('Prednisona', 'Prednisona', 'Comprimido', 5, 'mg', 'Corticoide', true),
  ('Prednisona', 'Prednisona', 'Comprimido', 20, 'mg', 'Corticoide', true),
  ('Prednisona', 'Prednisona', 'Suspensión oral', 20, 'mg/5mL', 'Corticoide', true),
  ('Hidrocortisona acetato', 'Hidrocortisona acetato', 'Crema', 1, '%', 'Corticoide tópico', true),
  ('Hidrocortisona succinato', 'Hidrocortisona succinato', 'Polvo para solución inyectable', 100, 'mg', 'Corticoide', true),
  ('Hidrocortisona succinato', 'Hidrocortisona succinato', 'Polvo para solución inyectable', 500, 'mg', 'Corticoide', true),
  ('Clobetasol', 'Clobetasol', 'Crema', 0.05, '%', 'Corticoide tópico', true),
  ('Cetirizina', 'Cetirizina', 'Comprimido', 10, 'mg', 'Antihistamínico', true),
  ('Levocetirizina', 'Levocetirizina', 'Jarabe', 5, 'mg/5mL', 'Antihistamínico', true),
  ('Loratadina', 'Loratadina', 'Comprimido', 10, 'mg', 'Antihistamínico', true),
  ('Loratadina', 'Loratadina', 'Jarabe', 5, 'mg/5mL', 'Antihistamínico', true),
  ('Desloratadina', 'Desloratadina', 'Comprimido', 5, 'mg', 'Antihistamínico', true),
  ('Clorfenamina', 'Clorfenamina', 'Comprimido', 4, 'mg', 'Antihistamínico', true),
  ('Clorfenamina', 'Clorfenamina', 'Solución inyectable', 10, 'mg/mL', 'Antihistamínico', true),
  ('Alprazolam', 'Alprazolam', 'Comprimido', 0.5, 'mg', 'Ansiolítico', true),
  ('Clonazepam', 'Clonazepam', 'Comprimido', 0.5, 'mg', 'Ansiolítico', true),
  ('Clonazepam', 'Clonazepam', 'Comprimido', 2, 'mg', 'Ansiolítico', true),
  ('Clotiazepam', 'Clotiazepam', 'Comprimido', 10, 'mg', 'Ansiolítico', true),
  ('Diazepam', 'Diazepam', 'Comprimido', 10, 'mg', 'Ansiolítico', true),
  ('Diazepam', 'Diazepam', 'Solución inyectable', 10, 'mg/mL', 'Ansiolítico', true),
  ('Lorazepam', 'Lorazepam', 'Comprimido', 2, 'mg', 'Ansiolítico', true),
  ('Lorazepam', 'Lorazepam', 'Comprimido sublingual', 2, 'mg', 'Ansiolítico', true),
  ('Lorazepam', 'Lorazepam', 'Solución inyectable', 4, 'mg/mL', 'Ansiolítico', true),
  ('Midazolam', 'Midazolam', 'Solución inyectable', 5, 'mg/mL', 'Ansiolítico', true),
  ('Eszopiclona', 'Eszopiclona', 'Comprimido', 3, 'mg', 'Hipnótico', true),
  ('Zolpidem', 'Zolpidem', 'Comprimido', 10, 'mg', 'Hipnótico', true),
  ('Trazodona', 'Trazodona', 'Comprimido', 25, 'mg', 'Antidepresivo', true),
  ('Trazodona', 'Trazodona', 'Comprimido', 100, 'mg', 'Antidepresivo', true),
  ('Citalopram', 'Citalopram', 'Comprimido', 20, 'mg', 'ISRS', true),
  ('Escitalopram', 'Escitalopram', 'Comprimido', 10, 'mg', 'ISRS', true),
  ('Fluoxetina', 'Fluoxetina', 'Comprimido', 20, 'mg', 'ISRS', true),
  ('Paroxetina', 'Paroxetina', 'Comprimido', 20, 'mg', 'ISRS', true),
  ('Sertralina', 'Sertralina', 'Comprimido', 50, 'mg', 'ISRS', true),
  ('Mirtazapina', 'Mirtazapina', 'Comprimido', 15, 'mg', 'Antidepresivo', true),
  ('Mirtazapina', 'Mirtazapina', 'Comprimido', 30, 'mg', 'Antidepresivo', true),
  ('Venlafaxina', 'Venlafaxina', 'Comprimido liberación prolongada', 75, 'mg', 'Antidepresivo', true),
  ('Duloxetina', 'Duloxetina', 'Comprimido', 30, 'mg', 'Antidepresivo', true),
  ('Imipramina', 'Imipramina', 'Comprimido', 25, 'mg', 'Antidepresivo', true),
  ('Amitriptilina', 'Amitriptilina', 'Comprimido', 25, 'mg', 'Antidepresivo', true),
  ('Clorpromazina', 'Clorpromazina', 'Comprimido', 25, 'mg', 'Antipsicótico', true),
  ('Clorpromazina', 'Clorpromazina', 'Comprimido', 100, 'mg', 'Antipsicótico', true),
  ('Clorpromazina', 'Clorpromazina', 'Solución inyectable', 12.5, 'mg/mL', 'Antipsicótico', true),
  ('Haloperidol', 'Haloperidol', 'Comprimido', 1, 'mg', 'Antipsicótico', true),
  ('Haloperidol', 'Haloperidol', 'Comprimido', 5, 'mg', 'Antipsicótico', true),
  ('Haloperidol', 'Haloperidol', 'Solución inyectable', 5, 'mg/mL', 'Antipsicótico', true),
  ('Flufenazina decanoato', 'Flufenazina decanoato', 'Solución inyectable', 25, 'mg/mL', 'Antipsicótico', true),
  ('Risperidona', 'Risperidona', 'Comprimido', 1, 'mg', 'Antipsicótico', true),
  ('Risperidona', 'Risperidona', 'Comprimido', 3, 'mg', 'Antipsicótico', true),
  ('Risperidona', 'Risperidona', 'Solución oral gotas', 1, 'mg/mL', 'Antipsicótico', true),
  ('Olanzapina', 'Olanzapina', 'Comprimido', 10, 'mg', 'Antipsicótico', true),
  ('Quetiapina', 'Quetiapina', 'Comprimido', 25, 'mg', 'Antipsicótico', true),
  ('Quetiapina', 'Quetiapina', 'Comprimido', 100, 'mg', 'Antipsicótico', true),
  ('Aripiprazol', 'Aripiprazol', 'Comprimido', 10, 'mg', 'Antipsicótico', true),
  ('Litio carbonato', 'Litio carbonato', 'Comprimido', 300, 'mg', 'Estabilizador del ánimo', true),
  ('Disulfiram', 'Disulfiram', 'Comprimido', 500, 'mg', 'Antialcohólico', true),
  ('Anfetamina', 'Anfetamina', 'Comprimido', 10, 'mg', 'Estimulante', true),
  ('Metilfenidato', 'Metilfenidato', 'Comprimido', 10, 'mg', 'Estimulante', true),
  ('Metilfenidato', 'Metilfenidato', 'Comprimido liberación prolongada', 20, 'mg', 'Estimulante', true),
  ('Ácido valproico', 'Ácido valproico', 'Comprimido', 200, 'mg', 'Anticonvulsivante', true),
  ('Ácido valproico', 'Ácido valproico', 'Comprimido', 250, 'mg', 'Anticonvulsivante', true),
  ('Ácido valproico', 'Ácido valproico', 'Solución oral gotas', 10, 'mg/gota', 'Anticonvulsivante', true),
  ('Divalproato', 'Divalproato', 'Comprimido liberación prolongada', 500, 'mg', 'Anticonvulsivante', true),
  ('Carbamazepina', 'Carbamazepina', 'Comprimido', 200, 'mg', 'Anticonvulsivante', true),
  ('Carbamazepina', 'Carbamazepina', 'Comprimido liberación prolongada', 400, 'mg', 'Anticonvulsivante', true),
  ('Fenitoína', 'Fenitoína', 'Comprimido', 100, 'mg', 'Anticonvulsivante', true),
  ('Fenitoína', 'Fenitoína', 'Solución inyectable', 50, 'mg/mL', 'Anticonvulsivante', true),
  ('Fenobarbital', 'Fenobarbital', 'Comprimido', 15, 'mg', 'Anticonvulsivante', true),
  ('Fenobarbital', 'Fenobarbital', 'Comprimido', 100, 'mg', 'Anticonvulsivante', true),
  ('Lamotrigina', 'Lamotrigina', 'Comprimido', 50, 'mg', 'Anticonvulsivante', true),
  ('Lamotrigina', 'Lamotrigina', 'Comprimido', 100, 'mg', 'Anticonvulsivante', true),
  ('Levetiracetam', 'Levetiracetam', 'Comprimido', 500, 'mg', 'Anticonvulsivante', true),
  ('Levetiracetam', 'Levetiracetam', 'Comprimido', 1000, 'mg', 'Anticonvulsivante', true),
  ('Levetiracetam', 'Levetiracetam', 'Jarabe', 100, 'mg/mL', 'Anticonvulsivante', true),
  ('Pregabalina', 'Pregabalina', 'Comprimido', 75, 'mg', 'Neuropático', true),
  ('Topiramato', 'Topiramato', 'Comprimido', 25, 'mg', 'Anticonvulsivante', true),
  ('Primidona', 'Primidona', 'Comprimido', 250, 'mg', 'Anticonvulsivante', true),
  ('Clonixinato de lisina', 'Clonixinato de lisina', 'Comprimido', 125, 'mg', 'Analgésico', true),
  ('Flunarizina', 'Flunarizina', 'Comprimido', 10, 'mg', 'Antimigrañoso', true),
  ('Ciclobenzaprina', 'Ciclobenzaprina', 'Comprimido', 10, 'mg', 'Relajante muscular', true),
  ('Donepezilo', 'Donepezilo', 'Comprimido', 10, 'mg', 'Anticolinesterásico', true),
  ('Levodopa + Benserazida', 'Levodopa + Benserazida', 'Comprimido', 250, 'mg', 'Antiparkinsoniano', true),
  ('Levodopa + Carbidopa', 'Levodopa + Carbidopa', 'Comprimido', 275, 'mg', 'Antiparkinsoniano', true),
  ('Pramipexol', 'Pramipexol', 'Comprimido', 0.25, 'mg', 'Antiparkinsoniano', true),
  ('Pramipexol', 'Pramipexol', 'Comprimido', 1, 'mg', 'Antiparkinsoniano', true),
  ('Trihexifenidilo', 'Trihexifenidilo', 'Comprimido', 2, 'mg', 'Antiparkinsoniano', true),
  ('Estradiol', 'Estradiol', 'Comprimido', 1, 'mg', 'Estrógeno', true),
  ('Estradiol gel', 'Estradiol gel', 'Gel transdérmico', 0.1, '%', 'Estrógeno', true),
  ('Tibolona', 'Tibolona', 'Comprimido', 2.5, 'mg', 'Hormonal', true),
  ('Progesterona micronizada', 'Progesterona micronizada', 'Cápsula', 100, 'mg', 'Progestágeno', true),
  ('Etonogestrel', 'Etonogestrel', 'Implante subdérmico', 68, 'mg', 'Anticonceptivo', true),
  ('Etonogestrel + Etinilestradiol', 'Etonogestrel + Etinilestradiol', 'Anillo vaginal', 14.4, 'mg', 'Anticonceptivo', true),
  ('Levonorgestrel', 'Levonorgestrel', 'Comprimido', 0.03, 'mg', 'Anticonceptivo', true),
  ('Levonorgestrel', 'Levonorgestrel', 'Comprimido', 1.5, 'mg', 'Anticonceptivo emergencia', true),
  ('Levonorgestrel', 'Levonorgestrel', 'Dispositivo intrauterino', 20, 'µg/24h', 'Anticonceptivo', true),
  ('Levonorgestrel', 'Levonorgestrel', 'Implante subdérmico', 75, 'mg', 'Anticonceptivo', true),
  ('Levonorgestrel + Etinilestradiol', 'Levonorgestrel + Etinilestradiol', 'Comprimido', 0.18, 'mg', 'Anticonceptivo', true),
  ('Medroxiprogesterona', 'Medroxiprogesterona', 'Jeringa prellenada', 104, 'mg/0.65mL', 'Anticonceptivo', true),
  ('Medroxiprogesterona', 'Medroxiprogesterona', 'Jeringa prellenada', 150, 'mg/mL', 'Anticonceptivo', true),
  ('Medroxiprogesterona + Estradiol', 'Medroxiprogesterona + Estradiol', 'Solución inyectable', 30, 'mg/0.5mL', 'Anticonceptivo', true),
  ('Noretisterona enantato + Estradiol valeriato', 'Noretisterona enantato + Estradiol valeriato', 'Comprimido', 55, 'mg', 'Hormonal', true),
  ('Carbetocin', 'Carbetocin', 'Solución inyectable', 100, 'µg/mL', 'Oxitócico', true),
  ('Oxitocina', 'Oxitocina', 'Solución inyectable', 5, 'UI/mL', 'Oxitócico', true),
  ('Misoprostol', 'Misoprostol', 'Comprimido', 200, 'µg', 'Prostaglandina', true),
  ('Fenoterol', 'Fenoterol', 'Solución inyectable', 0.05, 'mg/mL', 'Tocolítico', true),
  ('Sildenafil', 'Sildenafil', 'Comprimido', 50, 'mg', 'Disfunción eréctil', true),
  ('Tamsulosina', 'Tamsulosina', 'Comprimido', 0.4, 'mg', 'Hiperplasia prostática', true),
  ('Oxibutinina', 'Oxibutinina', 'Comprimido', 5, 'mg', 'Vejiga hiperactiva', true),
  ('Lubricante íntimo', 'Lubricante íntimo', 'Gel', 1, 'aplicación', 'Lubricante', true),
  ('Cloranfenicol oftálmico', 'Cloranfenicol oftálmico', 'Solución oftálmica', 0.5, '%', 'Antibiótico oftálmico', true),
  ('Cloranfenicol oftálmico', 'Cloranfenicol oftálmico', 'Ungüento oftálmico', 1, '%', 'Antibiótico oftálmico', true),
  ('Gentamicina oftálmica', 'Gentamicina oftálmica', 'Solución oftálmica', 0.3, '%', 'Antibiótico oftálmico', true),
  ('Ciprofloxacino ótico', 'Ciprofloxacino ótico', 'Solución ótica', 0.3, '%', 'Antibiótico ótico', true),
  ('Bacitracina + Neomicina', 'Bacitracina + Neomicina', 'Ungüento tópico', 50000, 'UI/g', 'Antibiótico tópico', true),
  ('Mupirocina', 'Mupirocina', 'Crema', 2, '%', 'Antibiótico tópico', true),
  ('Proparacaína', 'Proparacaína', 'Solución oftálmica', 5, 'mg/mL', 'Anestésico oftálmico', true),
  ('Alopurinol', 'Alopurinol', 'Comprimido', 100, 'mg', 'Antigotoso', true),
  ('Alopurinol', 'Alopurinol', 'Comprimido', 300, 'mg', 'Antigotoso', true),
  ('Colchicina', 'Colchicina', 'Comprimido', 0.5, 'mg', 'Antigotoso', true),
  ('Hidroxicloroquina', 'Hidroxicloroquina', 'Comprimido', 200, 'mg', 'Inmunomodulador', true),
  ('Sulfasalazina', 'Sulfasalazina', 'Comprimido', 500, 'mg', 'Inmunomodulador', true),
  ('Metotrexato', 'Metotrexato', 'Comprimido', 2.5, 'mg', 'Inmunosupresor', true),
  ('Azatioprina', 'Azatioprina', 'Comprimido', 50, 'mg', 'Inmunosupresor', true),
  ('Leflunomida', 'Leflunomida', 'Comprimido', 20, 'mg', 'Inmunosupresor', true),
  ('Ácido zoledrónico', 'Ácido zoledrónico', 'Solución inyectable', 4, 'mg/5mL', 'Bisfosfonato', true),
  ('Pamidronato', 'Pamidronato', 'Liofilizado para solución inyectable', 30, 'mg', 'Bisfosfonato', true),
  ('Pamidronato', 'Pamidronato', 'Liofilizado para solución inyectable', 90, 'mg', 'Bisfosfonato', true),
  ('Flumazenil', 'Flumazenil', 'Solución inyectable', 0.1, 'mg/mL', 'Antagonista BZD', true),
  ('Atropina', 'Atropina', 'Solución inyectable', 1, 'mg/mL', 'Anticolinérgico', true),
  ('Lidocaína', 'Lidocaína', 'Solución inyectable', 2, '%', 'Anestésico local', true),
  ('Lidocaína', 'Lidocaína', 'Gel tópico', 4, '%', 'Anestésico local', true),
  ('Lidocaína', 'Lidocaína', 'Carpule odontológico', 2, '%', 'Anestésico local', true),
  ('Etomidato', 'Etomidato', 'Solución inyectable', 2, 'mg/mL', 'Anestésico', true),
  ('Suxametonio (Succinilcolina)', 'Suxametonio (Succinilcolina)', 'Solución inyectable', 20, 'mg/mL', 'Bloqueante neuromuscular', true),
  ('Rocuronio', 'Rocuronio', 'Solución inyectable', 10, 'mg/mL', 'Bloqueante neuromuscular', true),
  ('Suero fisiológico', 'Suero fisiológico', 'Solución inyectable', 0.9, '%', 'Solución', true),
  ('Suero glucosado', 'Suero glucosado', 'Solución inyectable', 5, '%', 'Solución', true),
  ('Suero glucosado', 'Suero glucosado', 'Solución inyectable', 10, '%', 'Solución', true),
  ('Suero glucosado', 'Suero glucosado', 'Solución inyectable', 30, '%', 'Solución', true),
  ('Glucosa polvo', 'Glucosa polvo', 'Polvo oral', 75, 'g', 'Solución', true),
  ('Suero Ringer Lactato', 'Suero Ringer Lactato', 'Solución inyectable', 1000, 'mL', 'Solución', true),
  ('Cloruro de sodio', 'Cloruro de sodio', 'Solución inyectable', 10, '%', 'Electrolito', true),
  ('Cloruro de potasio', 'Cloruro de potasio', 'Comprimido', 600, 'mg', 'Electrolito', true),
  ('Cloruro de potasio', 'Cloruro de potasio', 'Solución inyectable', 10, '%', 'Electrolito', true),
  ('Bicarbonato de sodio', 'Bicarbonato de sodio', 'Solución inyectable', 8.4, '%', 'Electrolito', true),
  ('Calcio gluconato', 'Calcio gluconato', 'Solución inyectable', 10, '%', 'Electrolito', true),
  ('Magnesio sulfato', 'Magnesio sulfato', 'Solución inyectable', 25, '%', 'Electrolito', true),
  ('Sales rehidratantes 60', 'Sales rehidratantes 60', 'Solución oral', 60, 'mEq Na/L', 'Hidratación', true),
  ('Sales rehidratantes 90', 'Sales rehidratantes 90', 'Solución oral', 90, 'mEq Na/L', 'Hidratación', true),
  ('Albúmina sérica humana', 'Albúmina sérica humana', 'Solución inyectable', 20, '%', 'Coloide', true),
  ('Gammaglobulina humana anti-D', 'Gammaglobulina humana anti-D', 'Suspensión inyectable', 1, 'dosis', 'Inmunoglobulina', true),
  ('Agua bidestilada', 'Agua bidestilada', 'Solución inyectable', 5, 'mL', 'Solvente', true),
  ('Alcohol etílico 70°', 'Alcohol etílico 70°', 'Solución desnaturalizada', 70, '°', 'Antiséptico', true),
  ('Clorhexidina colutorio', 'Clorhexidina colutorio', 'Colutorio dental', 0.12, '%', 'Antiséptico oral', true),
  ('Clorhexidina solución', 'Clorhexidina solución', 'Solución', 1, '%', 'Antiséptico', true),
  ('Clorhexidina jabón 2%', 'Clorhexidina jabón 2%', 'Solución jabonosa', 2, '%', 'Antiséptico', true),
  ('Clorhexidina jabón 4%', 'Clorhexidina jabón 4%', 'Solución jabonosa', 4, '%', 'Antiséptico', true),
  ('Triclosán', 'Triclosán', 'Jabón líquido', 1, '%', 'Antiséptico', true),
  ('Flúor barniz', 'Flúor barniz', 'Barniz tópico', 5, '%', 'Odontológico', true),
  ('Fluoruro de sodio', 'Fluoruro de sodio', 'Colutorio dental', 0.05, '%', 'Odontológico', true),
  ('Vaselina sólida', 'Vaselina sólida', 'Pomada', 1, 'g', 'Emoliente', true),
  ('Vaselina líquida', 'Vaselina líquida', 'Aceite mineral', 250, 'mL', 'Emoliente', true),
  ('Vaselina azufrada', 'Vaselina azufrada', 'Ungüento', 6, '%', 'Tópico', true),
  ('Pasta Lassar (Óxido de zinc)', 'Pasta Lassar (Óxido de zinc)', 'Pomada', 2, '%', 'Tópico', true),
  ('Trimebutino', 'Trimebutino', 'Comprimido', 100, 'mg', 'Espasmolítico', true),
  ('Neomicina', 'Neomicina', 'Comprimido', 500, 'mg', 'Antibiótico', true),
  ('Enema evacuante (Fosfato)', 'Enema evacuante (Fosfato)', 'Enema', 130, 'mL', 'Laxante', true),
  ('Solución oral evacuante', 'Solución oral evacuante', 'Solución oral', 1, 'frasco', 'Preparación examen', true),
  ('Oxígeno', 'Oxígeno', 'Gas medicinal', 1, 'unidad', 'Gas', true),
  ('Óxido nitroso', 'Óxido nitroso', 'Gas medicinal', 1, 'unidad', 'Gas', true);

-- Arsenal SSÑ-2026 v2 (28 medicamentos, tag [SSÑ-2026])
insert into public.medications (name, active_ingredient, presentation, dose_value, dose_unit, category, restrictions, is_active) values
  ('Anfebutamona (Bupropion)', 'Bupropion', 'Comprimido liberación prolongada', 150, 'mg', 'Antidepresivo', '[SSÑ-2026] GES cesación del consumo de tabaco (PM)', true),
  ('Budesonida + Formoterol', 'Budesonida + Formoterol', 'Inhalador', 160, 'mcg/4.5mcg/dosis', 'Combinación inhalada', '[SSÑ-2026] PM Salud Respiratoria', true),
  ('Clobazam', 'Clobazam', 'Comprimido', 10, 'mg', 'Benzodiacepina', '[SSÑ-2026] PM Epilepsia', true),
  ('Lacosamida', 'Lacosamida', 'Comprimido', 100, 'mg', 'Anticonvulsivante', '[SSÑ-2026] PM Epilepsia', true),
  ('Oxcarbazepina', 'Oxcarbazepina', 'Comprimido', 300, 'mg', 'Anticonvulsivante', '[SSÑ-2026] PM Epilepsia', true),
  ('Oxcarbazepina', 'Oxcarbazepina', 'Suspensión oral', 60, 'mg/mL', 'Anticonvulsivante', '[SSÑ-2026] PM Epilepsia', true),
  ('Vigabatrina', 'Vigabatrina', 'Comprimido', 500, 'mg', 'Anticonvulsivante', '[SSÑ-2026] PM Epilepsia', true),
  ('Empagliflozina', 'Empagliflozina', 'Comprimido', 10, 'mg', 'Antidiabético', '[SSÑ-2026] Alternativa Dapagliflozina (PSCV, según protocolo)', true),
  ('Escopolamina', 'Escopolamina', 'Solución inyectable', 20, 'mg/mL', 'Antiespasmódico', '[SSÑ-2026] CPU', true),
  ('Fluticasona', 'Fluticasona', 'Inhalador', 125, 'mcg/dosis', 'Corticoide inhalado', '[SSÑ-2026] PM Salud Respiratoria', true),
  ('Ketamina', 'Ketamina', 'Solución inyectable', 500, 'mg/mL', 'Anestésico', '[SSÑ-2026] SRI / dolor refractario / agitación severa / crisis asmática severa', true),
  ('Rivaroxabán', 'Rivaroxabán', 'Comprimido', 20, 'mg', 'Anticoagulante', '[SSÑ-2026] Continuidad de tratamiento iniciado en especialidad', true),
  ('Tramadol + Paracetamol', 'Tramadol + Paracetamol', 'Comprimido', 325, 'mg/37.5mg', 'Opioide', '[SSÑ-2026] CPU', true),
  ('Ácido valproico', 'Ácido valproico', 'Jarabe', 250, 'mg/5mL', 'Anticonvulsivante', '[SSÑ-2026] PM Epilepsia', true),
  ('Ácido valproico', 'Ácido valproico', 'Comprimido liberación prolongada', 250, 'mg', 'Anticonvulsivante', '[SSÑ-2026] PM Epilepsia', true),
  ('Ácido valproico', 'Ácido valproico', 'Solución oral gotas', 375, 'mg/mL', 'Anticonvulsivante', '[SSÑ-2026] PM Epilepsia', true),
  ('Amoxicilina + Ácido clavulánico', 'Amoxicilina + Ácido clavulánico', 'Comprimido', 1000, 'mg (875+125)', 'Antibiótico', '[SSÑ-2026] Grupo de acceso (PROA)', true),
  ('Amoxicilina + Ácido clavulánico', 'Amoxicilina + Ácido clavulánico', 'Suspensión oral', 457, 'mg/5mL (400+57)', 'Antibiótico', '[SSÑ-2026] Grupo de acceso (PROA)', true),
  ('Calcio + Vitamina D', 'Calcio + Vitamina D', 'Comprimido', 500, 'mg + 800UI', 'Suplemento', '[SSÑ-2026] GES Cirrosis hepática', true),
  ('Calcio + Vitamina D', 'Calcio + Vitamina D', 'Comprimido', 450, 'mg + 175UI', 'Suplemento', '[SSÑ-2026]', true),
  ('Carbamazepina', 'Carbamazepina', 'Comprimido liberación prolongada', 200, 'mg', 'Anticonvulsivante', '[SSÑ-2026] PM Epilepsia', true),
  ('Fierro fumarato + Vitaminas + Ácido fólico', 'Hierro fumarato + Vitaminas + Ácido fólico', 'Comprimido', 1, 'comp', 'Suplemento', '[SSÑ-2026]', true),
  ('Flucloxacilina', 'Flucloxacilina', 'Comprimido', 500, 'mg', 'Antibiótico', '[SSÑ-2026] Grupo de acceso (PROA)', true),
  ('Lamotrigina', 'Lamotrigina', 'Comprimido bucodispersable', 25, 'mg', 'Anticonvulsivante', '[SSÑ-2026] PM Epilepsia', true),
  ('Morfina', 'Morfina', 'Comprimido liberación prolongada', 30, 'mg', 'Opioide', '[SSÑ-2026] CPU', true),
  ('Nifedipino', 'Nifedipino', 'Comprimido', 10, 'mg', 'Tocolítico', '[SSÑ-2026] Atención de parto prematuro', true),
  ('Topiramato', 'Topiramato', 'Comprimido', 100, 'mg', 'Anticonvulsivante', '[SSÑ-2026] PM Epilepsia', true),
  ('Tramadol', 'Tramadol', 'Comprimido liberación prolongada', 100, 'mg', 'Opioide', '[SSÑ-2026] CPU', true);
